name: Test App

on: [push, pull_request]

jobs:
  test:    
    # Make the workspace root importable as a module 
    env:
      PYTHONPATH: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Docker image
        run: docker build -t data-analyst-agent .
      - name: Run tests inside container
        run: docker run --rm data-analyst-agent pytest -q
      - name: Run tests
        run: |
          pytest
